name 'maestrodev-activemq'
version '0.0.1'

author 'maestrodev'
license 'Apache License, Version 2.0'
project_page 'http://github.com/maestrodev/puppet-activemq'
source 'http://github.com/maestrodev/puppet-activemq'
summary 'Apache ActiveMQ module for Puppet'
description 'A Puppet module to install ActiveMQ'
dependency 'maestrodev/wget', '>=0.0.1'
